# Generated by Django 5.2.9 on 2026-02-11 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lexicon', '0009_translationbatch_wordtranslation_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alt_names', models.TextField(blank=True, help_text='Comma-separated alternative names')),
                ('family', models.CharField(blank=True, default='Niger-Congo', max_length=128)),
                ('branch', models.CharField(blank=True, max_length=128)),
                ('iso_639_3', models.CharField(blank=True, max_length=3, verbose_name='ISO 639-3')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('trust_level', models.CharField(choices=[('new', 'New (weight 1)'), ('regular', 'Regular (weight 2)'), ('trusted', 'Trusted (weight 3)'), ('admin', 'Admin (weight 5)'), ('owner', 'Owner (weight 10)')], default='new', max_length=16)),
                ('accepted_contributions', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_profile', to=settings.AUTH_USER_MODEL)),
                ('languages_spoken', models.ManyToManyField(blank=True, to='comparisons.language')),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='LexicalComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew_word', models.CharField(help_text='Hebrew form (pointed)', max_length=128)),
                ('hebrew_transliteration', models.CharField(blank=True, max_length=128)),
                ('hebrew_root', models.CharField(blank=True, max_length=32)),
                ('hebrew_meaning', models.CharField(max_length=255)),
                ('nc_word', models.CharField(max_length=128, verbose_name='Niger-Congo word')),
                ('nc_transliteration', models.CharField(blank=True, max_length=128, verbose_name='NC transliteration')),
                ('nc_meaning', models.CharField(max_length=255, verbose_name='NC meaning')),
                ('nc_usage_example', models.TextField(blank=True, verbose_name='NC usage example')),
                ('category', models.CharField(choices=[('cognate', 'Cognate'), ('semantic', 'Semantic parallel'), ('phrase', 'Phrasal parallel'), ('phonetic', 'Phonetic similarity'), ('grammatical', 'Grammatical parallel'), ('other', 'Other')], default='cognate', max_length=16)),
                ('semantic_domain', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, help_text='e.g. oral tradition, published research', max_length=64)),
                ('source_reference', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('accepted', 'Accepted'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked entries cannot receive votes')),
                ('confidence_score', models.IntegerField(default=0, help_text='Denormalized sum of active vote weights')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False, help_text='Soft delete')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comparisons', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='comparisons.language')),
                ('lexeme', models.ForeignKey(blank=True, help_text="Optional link to Strong's lexeme", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to='lexicon.lexeme')),
            ],
            options={
                'verbose_name': 'Lexical Comparison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inaccurate', 'Inaccurate'), ('duplicate', 'Duplicate'), ('spam', 'Spam'), ('offensive', 'Offensive'), ('other', 'Other')], max_length=16)),
                ('explanation', models.TextField(blank=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='comparisons.lexicalcomparison')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('data', models.JSONField(help_text='Snapshot of the comparison fields at this revision')),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='comparisons.lexicalcomparison')),
            ],
            options={
                'ordering': ['comparison', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Agree (+1)'), (-1, 'Disagree (-1)')])),
                ('weight', models.SmallIntegerField(help_text='trust_weight × value, stamped at vote time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='comparisons.lexicalcomparison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lexicalcomparison',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('hebrew_word', 'language', 'nc_word'), name='unique_comparison_not_removed'),
        ),
        migrations.AlterUniqueTogether(
            name='comparisonrevision',
            unique_together={('comparison', 'revision_number')},
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('comparison', 'user'), name='one_vote_per_user_per_comparison'),
        ),
    ]
