# Generated by Django 5.2.9 on 2026-02-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('strongs_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('hebrew', 'Hebrew'), ('greek', 'Greek')], max_length=10)),
                ('lemma', models.CharField(max_length=128)),
                ('transliteration', models.CharField(blank=True, max_length=128)),
                ('gloss', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['strongs_id'],
            },
        ),
    ]
