# Generated by Django 5.2.9 on 2026-02-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexeme',
            name='gloss',
            field=models.TextField(blank=True),
        ),
    ]
