# Generated by Django 5.2.9 on 2026-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_alter_lexeme_gloss'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexeme',
            name='definition',
            field=models.TextField(blank=True),
        ),
    ]
