# Generated by Django 5.2.9 on 2026-02-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_lexeme_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osis_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('testament', models.CharField(choices=[('ot', 'Old Testament'), ('nt', 'New Testament')], max_length=2)),
                ('canonical_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['canonical_order'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('osis_id', models.CharField(max_length=32, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.book')),
            ],
            options={
                'ordering': ['book__canonical_order', 'chapter', 'verse'],
                'unique_together': {('book', 'chapter', 'verse')},
            },
        ),
        migrations.CreateModel(
            name='WordOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('language', models.CharField(choices=[('hebrew', 'Hebrew'), ('greek', 'Greek')], max_length=10)),
                ('surface', models.TextField(blank=True)),
                ('lemma', models.TextField(blank=True)),
                ('morphology', models.CharField(blank=True, max_length=64)),
                ('strongs_id', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(max_length=32)),
                ('word_id', models.CharField(blank=True, max_length=64)),
                ('part_of_speech', models.CharField(blank=True, max_length=32)),
                ('parsing', models.CharField(blank=True, max_length=64)),
                ('variant', models.CharField(blank=True, max_length=64)),
                ('normalized', models.TextField(blank=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.verse')),
            ],
            options={
                'ordering': ['verse__book__canonical_order', 'verse__chapter', 'verse__verse', 'position'],
                'indexes': [models.Index(fields=['strongs_id'], name='lexicon_wor_strongs_87532f_idx'), models.Index(fields=['lemma'], name='lexicon_wor_lemma_6d6213_idx'), models.Index(fields=['language'], name='lexicon_wor_languag_8c0932_idx')],
            },
        ),
    ]
