# Generated by Django 5.2.9 on 2026-02-08 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_book_verse_wordoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebrewLexicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=128)),
                ('lemma_unpointed', models.CharField(max_length=128)),
                ('root', models.CharField(max_length=16)),
                ('root_consonants', models.CharField(max_length=32)),
                ('strongs', models.CharField(blank=True, max_length=10, null=True)),
                ('gloss_basic', models.CharField(blank=True, max_length=255, null=True)),
                ('sense', models.CharField(blank=True, max_length=255, null=True)),
                ('lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hebrew_occurrences', to='lexicon.lexeme')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hebrew_lexical', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Hebrew Lexical Info',
                'verbose_name_plural': 'Hebrew Lexical Info',
            },
        ),
        migrations.CreateModel(
            name='HebrewMorphAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=32)),
                ('subtype', models.CharField(blank=True, max_length=32, null=True)),
                ('binyan', models.CharField(blank=True, max_length=16, null=True)),
                ('conjugation', models.CharField(blank=True, max_length=32, null=True)),
                ('person', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('aspect', models.CharField(blank=True, max_length=16, null=True)),
                ('voice', models.CharField(blank=True, max_length=16, null=True)),
                ('mood', models.CharField(blank=True, max_length=16, null=True)),
                ('polarity', models.CharField(blank=True, max_length=16, null=True)),
                ('negation_particle', models.CharField(blank=True, max_length=16, null=True)),
                ('state', models.CharField(blank=True, max_length=16, null=True)),
                ('definiteness', models.CharField(blank=True, max_length=16, null=True)),
                ('suffix_person', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('suffix_gender', models.CharField(blank=True, max_length=16, null=True)),
                ('suffix_number', models.CharField(blank=True, max_length=16, null=True)),
                ('raw_morph_code', models.CharField(blank=True, max_length=64, null=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hebrew_analysis', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Hebrew Morphological Analysis',
                'verbose_name_plural': 'Hebrew Morphological Analyses',
            },
        ),
        migrations.CreateModel(
            name='HebrewMorpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_order', models.PositiveSmallIntegerField()),
                ('slot', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('form', models.CharField(max_length=64)),
                ('unpointed', models.CharField(max_length=64)),
                ('root', models.CharField(blank=True, max_length=16, null=True)),
                ('binyan', models.CharField(blank=True, max_length=16, null=True)),
                ('person', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('number', models.CharField(blank=True, max_length=16, null=True)),
                ('gloss', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebrew_morphemes', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Hebrew Morpheme',
                'verbose_name_plural': 'Hebrew Morphemes',
                'ordering': ['word', 'slot_order'],
            },
        ),
        migrations.CreateModel(
            name='HebrewTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('literal', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hebrew_translation', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Hebrew Translation',
                'verbose_name_plural': 'Hebrew Translations',
            },
        ),
    ]
