# Generated by Django 5.2.9 on 2026-02-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0005_hebrewlexicalinfo_hebrewmorphanalysis_hebrewmorpheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='wordoccurrence',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
