# Generated by Django 5.2.9 on 2026-02-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0006_add_slug_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='wordoccurrence',
            constraint=models.UniqueConstraint(fields=('verse', 'slug'), name='unique_word_slug_per_verse'),
        ),
    ]
