# Generated by Django 5.2.9 on 2026-02-10 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0007_enforce_slug_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('language_name', models.CharField(max_length=50)),
                ('phrase', models.CharField(max_length=255)),
                ('literal', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Word Translation',
                'verbose_name_plural': 'Word Translations',
                'ordering': ['language_code'],
                'unique_together': {('word', 'language_code')},
            },
        ),
    ]
