# Generated by Django 5.2.9 on 2026-02-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0008_wordtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('language_name', models.CharField(max_length=50)),
                ('prompt', models.TextField(blank=True)),
                ('raw_response', models.JSONField()),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_batches', to='lexicon.verse')),
            ],
            options={
                'verbose_name': 'Translation Batch',
                'verbose_name_plural': 'Translation Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='lexicon.translationbatch'),
        ),
    ]
