# Generated by Django 5.2.9 on 2026-02-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0009_translationbatch_wordtranslation_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('surface', models.CharField(max_length=128)),
                ('strongs_id', models.CharField(blank=True, max_length=10)),
                ('flag_type', models.CharField(choices=[('divergent', 'Divergent — major translations disagree'), ('rare', 'Rare — hapax legomenon or very low frequency'), ('uncertain', 'Uncertain — meaning debated among scholars')], max_length=16)),
                ('note', models.TextField(help_text='Explanation of what is uncertain or divergent')),
                ('sources_consulted', models.TextField(blank=True, help_text="References checked (Strong's, BDB, translations, etc.)")),
                ('resolution', models.TextField(blank=True, help_text='How this was resolved after human review')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_flags', to='lexicon.book')),
                ('word_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_flags', to='lexicon.wordoccurrence')),
            ],
            options={
                'verbose_name': 'Translation Flag',
                'verbose_name_plural': 'Translation Flags',
                'ordering': ['book__canonical_order', 'chapter', 'verse', 'position'],
            },
        ),
    ]
