# Generated by Django 5.2.9 on 2026-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0010_add_translation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtranslation',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
