BOOKS = [
    ("Gen", "Genesis", "ot", 1),
    ("Exod", "Exodus", "ot", 2),
    ("Lev", "Leviticus", "ot", 3),
    ("Num", "Numbers", "ot", 4),
    ("Deut", "Deuteronomy", "ot", 5),
    ("Josh", "Joshua", "ot", 6),
    ("Judg", "Judges", "ot", 7),
    ("Ruth", "Ruth", "ot", 8),
    ("1Sam", "1 Samuel", "ot", 9),
    ("2Sam", "2 Samuel", "ot", 10),
    ("1Kgs", "1 Kings", "ot", 11),
    ("2Kgs", "2 Kings", "ot", 12),
    ("1Chr", "1 Chronicles", "ot", 13),
    ("2Chr", "2 Chronicles", "ot", 14),
    ("Ezra", "Ezra", "ot", 15),
    ("Neh", "Nehemiah", "ot", 16),
    ("Esth", "Esther", "ot", 17),
    ("Job", "Job", "ot", 18),
    ("Ps", "Psalms", "ot", 19),
    ("Prov", "Proverbs", "ot", 20),
    ("Eccl", "Ecclesiastes", "ot", 21),
    ("Song", "Song of Songs", "ot", 22),
    ("Isa", "Isaiah", "ot", 23),
    ("Jer", "Jeremiah", "ot", 24),
    ("Lam", "Lamentations", "ot", 25),
    ("Ezek", "Ezekiel", "ot", 26),
    ("Dan", "Daniel", "ot", 27),
    ("Hos", "Hosea", "ot", 28),
    ("Joel", "Joel", "ot", 29),
    ("Amos", "Amos", "ot", 30),
    ("Obad", "Obadiah", "ot", 31),
    ("Jonah", "Jonah", "ot", 32),
    ("Mic", "Micah", "ot", 33),
    ("Nah", "Nahum", "ot", 34),
    ("Hab", "Habakkuk", "ot", 35),
    ("Zeph", "Zephaniah", "ot", 36),
    ("Hag", "Haggai", "ot", 37),
    ("Zech", "Zechariah", "ot", 38),
    ("Mal", "Malachi", "ot", 39),
    ("Matt", "Matthew", "nt", 40),
    ("Mark", "Mark", "nt", 41),
    ("Luke", "Luke", "nt", 42),
    ("John", "John", "nt", 43),
    ("Acts", "Acts", "nt", 44),
    ("Rom", "Romans", "nt", 45),
    ("1Cor", "1 Corinthians", "nt", 46),
    ("2Cor", "2 Corinthians", "nt", 47),
    ("Gal", "Galatians", "nt", 48),
    ("Eph", "Ephesians", "nt", 49),
    ("Phil", "Philippians", "nt", 50),
    ("Col", "Colossians", "nt", 51),
    ("1Thess", "1 Thessalonians", "nt", 52),
    ("2Thess", "2 Thessalonians", "nt", 53),
    ("1Tim", "1 Timothy", "nt", 54),
    ("2Tim", "2 Timothy", "nt", 55),
    ("Titus", "Titus", "nt", 56),
    ("Phlm", "Philemon", "nt", 57),
    ("Heb", "Hebrews", "nt", 58),
    ("Jas", "James", "nt", 59),
    ("1Pet", "1 Peter", "nt", 60),
    ("2Pet", "2 Peter", "nt", 61),
    ("1John", "1 John", "nt", 62),
    ("2John", "2 John", "nt", 63),
    ("3John", "3 John", "nt", 64),
    ("Jude", "Jude", "nt", 65),
    ("Rev", "Revelation", "nt", 66),
]

BOOKS_BY_OSIS = {osis: (name, testament, order) for osis, name, testament, order in BOOKS}

MORPHGNT_BOOK_MAP = {
    "Mt": "Matt",
    "Mk": "Mark",
    "Lk": "Luke",
    "Jn": "John",
    "Ac": "Acts",
    "Ro": "Rom",
    "1Co": "1Cor",
    "2Co": "2Cor",
    "Ga": "Gal",
    "Eph": "Eph",
    "Php": "Phil",
    "Col": "Col",
    "1Th": "1Thess",
    "2Th": "2Thess",
    "1Ti": "1Tim",
    "2Ti": "2Tim",
    "Tit": "Titus",
    "Phm": "Phlm",
    "Heb": "Heb",
    "Jas": "Jas",
    "1Pe": "1Pet",
    "2Pe": "2Pet",
    "1Jn": "1John",
    "2Jn": "2John",
    "3Jn": "3John",
    "Jud": "Jude",
    "Rev": "Rev",
}
